In [7]:

# Import libraries
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('..')

from src.clustering_library.__init__ import FeatureEngineer
from src.notebook_io import wpath, rpath   # manual runs write to data/_sandbox, never canonical

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import seaborn as sns

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [12]:
data_path = r"C:\Users\ACER\Documents\data_project\data\processed\cleaned_uk.csv"
raw_data_path = "data/raw/Online Retail.xlsx"

fe = FeatureEngineer(data_path, raw_data_path = raw_data_path)

In [14]:
df = fe.load_data()

2026-08-06 13:45:22,638 - INFO - Cleaned dataset shape: (354321, 11)
2026-08-06 13:45:22,639 - WARNING - raw_data_path not found (data/raw/Online Retail.xlsx). ReturnRate will be 0.

In [20]:
print(f"Dataset: {df.shape[0]} - Customers: {df['CustomerID'].nunique()}")
print(f"Data range: {df['InvoiceDate'].min().date()} -> {df['InvoiceDate'].max().date()}")

Dataset: 354321 - Customers: 3920
Data range: 2010-12-01 -> 2011-12-09

In [43]:
_compute_features = fe.create_customer_features()

2026-08-06 14:20:25,312 - INFO - [1/4] Purchase Rhythm...
2026-08-06 14:20:25,346 - INFO - [2/4] Spending Shape...
2026-08-06 14:20:25,583 - INFO - [3/4] Basket Behavior...
2026-08-06 14:20:26,553 - INFO - [4/4] Volume & Bulk...
2026-08-06 14:20:26,673 - WARNING - 70 NaN values — filling with column medians.
2026-08-06 14:20:26,682 - INFO - Computed 14 candidates for 3920 customers
2026-08-06 14:20:26,687 - INFO - Final feature set (14 features):
2026-08-06 14:20:26,691 - INFO -     total_orders
2026-08-06 14:20:26,694 - INFO -     recency
2026-08-06 14:20:26,697 - INFO -     inter_cv
2026-08-06 14:20:26,699 - INFO -     active_span
2026-08-06 14:20:26,701 - INFO -     monthly_rate
2026-08-06 14:20:26,704 - INFO -     AOV
2026-08-06 14:20:26,709 - INFO -     SpendGini
2026-08-06 14:20:26,711 - INFO -     PriceCV
2026-08-06 14:20:26,712 - INFO -     NewSKURate
2026-08-06 14:20:26,715 - INFO -     RepeatSKUFraction
2026-08-06 14:20:26,717 - INFO -     BasketSizeCV
2026-08-06 14:20:26,720 - INFO -     BurstIndex
2026-08-06 14:20:26,722 - INFO -     BulkLineRate
2026-08-06 14:20:26,724 - INFO -     QuantityCV

In [44]:
_compute_features.head()

,CustomerID,total_orders,recency,inter_cv,active_span,monthly_rate,AOV,SpendGini,PriceCV,NewSKURate,RepeatSKUFraction,BasketSizeCV,BurstIndex,BulkLineRate,QuantityCV
0,12346,1,326,0.00,0,1.00,77183.60,0.00,0.00,1.000000,0.000000,0.000000,1.000000,1.000000,0.868111
1,12747,11,2,0.48,366,0.90,40.74,0.45,0.76,0.386662,0.452381,0.341990,1.770534,0.310680,0.795643
2,12748,210,1,2.19,372,16.94,7.34,0.63,5.30,0.435008,0.561086,1.195062,12.561794,0.073341,3.236208
3,12749,5,4,0.98,209,0.72,20.56,0.22,0.95,0.635737,0.231250,0.746489,2.281208,0.065327,1.053320
4,12820,4,3,1.16,323,0.37,15.97,0.17,0.69,0.916667,0.072727,0.338418,1.459176,0.203390,0.644220

In [45]:
print("----Descriptive Statistics-----")
_compute_features.describe()

----Descriptive Statistics-----

,CustomerID,total_orders,recency,inter_cv,active_span,monthly_rate,AOV,SpendGini,PriceCV,NewSKURate,RepeatSKUFraction,BasketSizeCV,BurstIndex,BulkLineRate,QuantityCV
count,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000,3920.000000
mean,15562.059694,4.223724,92.208418,0.367584,131.021173,1.511661,71.758291,0.332026,0.916237,0.841026,0.140723,0.352258,1.436246,0.215017,0.980986
std,1576.594671,7.128801,99.533854,0.477355,132.271348,16.067484,1543.980072,0.147373,0.575722,0.198542,0.191592,0.364403,0.691793,0.250199,0.530755
min,12346.000000,1.000000,1.000000,0.000000,0.000000,0.160000,2.100000,0.000000,0.000000,0.081087,0.000000,0.000000,1.000000,0.000000,0.000000
25%,14208.750000,1.000000,18.000000,0.000000,0.000000,0.610000,11.195000,0.220000,0.710000,0.716908,0.000000,0.000000,1.000000,0.035714,0.662483
50%,15569.500000,2.000000,51.000000,0.000000,93.000000,1.000000,17.285000,0.330000,0.870000,0.935126,0.058824,0.290123,1.227272,0.127660,0.868111
75%,16913.250000,5.000000,143.000000,0.730000,252.000000,1.000000,24.390000,0.440000,1.020000,1.000000,0.224138,0.603764,1.636353,0.288717,1.182173
max,18287.000000,210.000000,374.000000,3.150000,373.000000,990.000000,77183.600000,0.890000,14.520000,1.000000,1.000000,2.025950,12.561794,1.000000,9.252898